### ISSUE TITLE
JSON for the swahili kamusi data 

### ISSUE THREAD

**Issue by Kalebu** [jacksiro254/Kamusi-Web#1]
Hello @jacksiro254 

Great work with [Kamusi-Web](https://github.com/jacksiro254/Kamusi-Web)

I'm currently working on collecting data for building one big language model which will later be open-sourced.

Can you please share the data,  JSON, or (any format they're in) so I can include them in the training data?

I will highly appreciate 

Best regards
Kalebu

**Comment by JacksiroKe** [comment]
Hello Kalebu,

Thanks for getting in touch with me on this. This is a project I have never been serious in because its sort of a side project most of the time. I dont if you have seen this project https://github.com/jacksiro254/Kamusi-Mobile. Especially if you open https://github.com/jacksiro254/Kamusi-Mobile/blob/main/lib/utils/strings/api_strings.dart you can access the info you need.

**Comment by Kalebu** [comment]
Hello @jacksiro254 

Thanks for the guidance, I struggled to access the data programmatically using API, but what I did is scraping the whole kamusi from [kamusi](http://kamusi.appsmata.com) using selenium.

You can view the data at [kamusi-data](https://github.com/Kalebu/kamusi)

Thank you so much 

Best regards
Kalebu
